"""
AhYakar — Multi-Agent Medical Assistant
========================================
Flask backend that orchestrates the four-agent pipeline:

  [1] Intake Analyst      — gatekeeper: home remedy vs escalate vs no-symptoms
  [2] Medical Advisor     — deep clinical analysis: OTC vs doctor vs emergency
  [3] Appointment Planner — finds nearest available doctor using patient location
  [4] Executor            — calls the booking API after user confirms

Session state is kept in-memory, keyed by a UUID generated by the browser
and persisted in localStorage for the duration of the tab/conversation.
"""

import os
import asyncio
import logging
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from flask import Flask, request, jsonify, render_template, send_from_directory
from openai import OpenAI

from agents import intake_analyst, medical_advisor, appointment_planner, executor, clinical_diagnostician

import uuid
import base64
from werkzeug.utils import secure_filename

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# ── OpenRouter client (lazy-initialized on first request) ──────────────────
_client: OpenAI | None = None

def get_client() -> OpenAI:
    """Return the singleton OpenRouter client, creating it on first call."""
    global _client
    if _client is None:
        api_key = os.getenv("OPENROUTER_API_KEY")
        if not api_key:
            raise RuntimeError(
                "OPENROUTER_API_KEY environment variable is not set. "
                "Please set it before starting the server."
            )
        _client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key,
        )
    return _client

import json

APP_DATA_DIR = 'app_data'
if not os.path.exists(APP_DATA_DIR):
    os.makedirs(APP_DATA_DIR)
DB_FILE = os.path.join(APP_DATA_DIR, 'db.json')

# ── Persistent session store ───────────────────────────────────────────────────
# Structure: { session_id: { chat_history, pending_action, last_triage } }
sessions: dict[str, dict] = {}
user_sessions: dict[str, list[str]] = {}
user_data: dict[str, dict] = {}

def load_state():
    global sessions, user_sessions, user_data
    if os.path.exists(DB_FILE):
        try:
            with open(DB_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                sessions = data.get('sessions', {})
                user_sessions = data.get('user_sessions', {})
                user_data = data.get('user_data', {})
        except Exception as e:
            logger.error("Failed to load state: %s", e)

def save_state():
    try:
        with open(DB_FILE, 'w', encoding='utf-8') as f:
            json.dump({
                'sessions': sessions,
                'user_sessions': user_sessions,
                'user_data': user_data
            }, f, ensure_ascii=False, indent=2)
    except Exception as e:
        logger.error("Failed to save state: %s", e)

load_state()

@app.after_request
def auto_save(response):
    if request.path.startswith('/api/'):
        save_state()
    return response

def get_user_data(user_id: str) -> dict:
    if user_id not in user_data:
        user_data[user_id] = {"medications": []}
    return user_data[user_id]

def get_session(session_id: str, user_id: str = None) -> dict:
    """Return (creating if needed) the session state for the given ID."""
    if session_id not in sessions:
        sessions[session_id] = {
            "chat_history": [],
            "pending_action": None,
            "last_triage": None,
            "patient_profile": {
                "symptoms": [],
                "duration": "unknown",
                "relevant_history": "none",
                "medications": []
            }
        }
        if user_id:
            if user_id not in user_sessions:
                user_sessions[user_id] = []
            if session_id not in user_sessions[user_id]:
                user_sessions[user_id].append(session_id)
    return sessions[session_id]


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def home():
    """Serve the web UI."""
    return render_template("index.html")


@app.route("/api/chat", methods=["POST"])
def chat():
    """Main pipeline endpoint."""
    data = request.json or {}
    user_message = (data.get("message") or "").strip()
    
    user_id = (data.get("userId") or "").strip()
    session_id = (data.get("sessionId") or user_id or data.get("session_id") or "").strip()
    location   = data.get("location")
    image_data = data.get("imageData") # Base64 string from client

    if not user_message and not image_data:
        return jsonify({"error": "message or image is required"}), 400
    if not session_id:
        return jsonify({"error": "sessionId is required"}), 400

    sess = get_session(session_id, user_id)
    sess["chat_history"].append({"role": "user", "content": user_message})

    try:
        client = get_client()

        # Generate a headline title if it doesn't exist
        if "title" not in sess and user_message:
            try:
                resp = client.chat.completions.create(
                    model="google/gemini-2.5-flash",
                    messages=[{"role": "user", "content": f"Provide a very short 2-5 word headline summarizing this medical complaint: '{user_message}'. Output only the headline."}],
                    max_tokens=20,
                    extra_headers={
                        "HTTP-Referer": "http://localhost:5000",
                        "X-OpenRouter-Title": "AhYakar",
                    }
                )
                sess["title"] = resp.choices[0].message.content.strip().replace('"', '')
            except Exception as e:
                logger.warning("Failed to generate title: %s", e)
                sess["title"] = user_message[:50] + "..."

        # ── Agent 1: Intake Analyst ──────────────────────────────────────────
        logger.info("[%s] Agent 1 — Intake Analyst (Vision: %s)", session_id[:8], bool(image_data))
        triage = intake_analyst.analyze(client, user_message, sess["chat_history"], image_data)
        sess["last_triage"] = triage
        
        # Merge memory into patient_profile
        profile = sess["patient_profile"]
        for sym in triage.get("symptoms", []):
            if sym.lower() not in [s.lower() for s in profile["symptoms"]]:
                profile["symptoms"].append(sym)
        
        if triage.get("duration") != "unknown":
            profile["duration"] = triage["duration"]
        if triage.get("relevant_history") != "none":
            profile["relevant_history"] = triage["relevant_history"]

        action1 = triage.get("action", "escalate")

        if action1 == "no_symptoms" and not profile["symptoms"]:
            reply = "I'm here to help with your health! Describe any symptoms you have."
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({
                "stage": "chat", 
                "reply": reply, 
                "requires_confirm": False,
                "thoughts": { "intake": triage }
            })

        # If we have symptoms in profile, but analyst says 'no_symptoms' for the latest word
        # (e.g. user said 'Yes' to a question), we should still escalate to advisor
        if action1 == "no_symptoms" and profile["symptoms"]:
            action1 = "escalate"

        if action1 == "home_remedy":
            reply = triage.get("home_remedy_advice") or "This sounds like it can be managed at home with rest and fluids."
            reply += "\n\n_I am an AI assistant, not a doctor._"
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({
                "stage": "home_remedy", 
                "reply": reply, 
                "requires_confirm": False,
                "thoughts": { "intake": triage }
            })

        # ── Agent 2: Clinical Diagnostician ──────────────────────────────────
        logger.info("[%s] Agent 2 — Clinical Diagnostician", session_id[:8])
        assessment = clinical_diagnostician.analyze(client, profile, sess["chat_history"], image_data)

        # ── Agent 3: Medical Advisor ─────────────────────────────────────────
        logger.info("[%s] Agent 3 — Medical Advisor", session_id[:8])
        advice = medical_advisor.advise(client, profile, assessment, sess["chat_history"])
        action2 = advice.get("action", "doctor_needed")

        # Save medications to user profile
        import datetime
        meds = advice.get("otc_medications", [])
        if meds and user_id:
            udata = get_user_data(user_id)
            current_date = datetime.datetime.now().strftime("%B %d, %Y")
            for med in meds:
                existing_texts = [m.get("text") if isinstance(m, dict) else m for m in udata["medications"]]
                if med not in existing_texts:
                    udata["medications"].append({"text": med, "date": current_date})

        if action2 == "emergency":
            reply = advice.get("reply") or "🚨 **Medical Emergency.** Call 101/911 immediately."
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({
                "stage": "emergency", 
                "reply": reply, 
                "requires_confirm": False,
                "thoughts": { "intake": triage, "advisor": advice }
            })

        if action2 == "otc":
            reply = advice.get("reply", "")
            if meds:
                raw_med_name = meds[0] if isinstance(meds[0], str) else meds[0].get("text")
                # Try to find dosage in the AI reply to include in search
                import re
                dosage_match = re.search(r'(\d+\s*mg)', advice.get("reply", ""), re.IGNORECASE)
                dosage = dosage_match.group(1) if dosage_match else ""
                
                # Clean up: use only the brand name for better compatibility across pharmacies
                med_name = raw_med_name.split('/')[0].split(' or ')[0].split(' and ')[0].split(' או ')[0].strip()
                search_query = med_name.strip()
                
                proposal_text = f"Would you like me to search local Israeli pharmacies for the best deal on {search_query}?"
                sess["pending_action"] = {
                    "type": "med_search",
                    "med_name": search_query
                }
                full_history = reply + f"\n\n{proposal_text}"
                sess["chat_history"].append({"role": "assistant", "content": full_history})
                return jsonify({
                    "stage": "otc", 
                    "reply": reply,
                    "proposal_text": proposal_text,
                    "requires_confirm": True,
                    "confirm_type": "med_search",
                    "thoughts": { "intake": triage, "advisor": advice }
                })
            else:
                sess["chat_history"].append({"role": "assistant", "content": reply})
                return jsonify({
                    "stage": "otc", 
                    "reply": reply, 
                    "requires_confirm": False,
                    "thoughts": { "intake": triage, "advisor": advice }
                })

        if action2 == "more_info_needed":
            reply = advice.get("reply", "")
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({"stage": "chat", "reply": reply, "requires_confirm": False})

        # Doctor needed → Agent 4: Appointment Planner
        logger.info("[%s] Agent 4 — Appointment Planner", session_id[:8])
        plan_result = appointment_planner.plan(client, triage, advice, location)
        proposal_text = plan_result.get("proposal_text", "")
        
        sess["pending_action"] = {
            "appointment_details": plan_result.get("appointment_details", {}),
            "triage": triage,
        }

        advisor_reply = advice.get("reply", "")
        full_history = advisor_reply + (f"\n\n{proposal_text}" if proposal_text else "")
        sess["chat_history"].append({"role": "assistant", "content": full_history})
        
        return jsonify({
            "stage": "doctor_needed",
            "reply": advisor_reply,
            "proposal": proposal_text,
            "requires_confirm": True,
            "thoughts": {
                "intake": triage,
                "advisor": advice,
                "planner": plan_result
            }
        })

    except Exception as exc:
        logger.exception("[%s] Pipeline error: %s", session_id[:8], exc)
        return jsonify({"error": str(exc)}), 500


@app.route("/api/confirm", methods=["POST"])
def confirm():
    """Confirmation endpoint — Phase 1: scan portal and return appointment options."""
    data = request.json or {}
    user_id = (data.get("userId") or "").strip()
    session_id = (data.get("sessionId") or user_id or data.get("session_id") or "").strip()
    confirmed  = bool(data.get("confirmed", False))

    if not session_id:
        return jsonify({"error": "sessionId is required"}), 400

    sess = get_session(session_id, user_id)
    pending = sess.get("pending_action")

    if not pending:
        return jsonify({"error": "No pending action"}), 400

    if pending.get("type") == "med_search":
        if not confirmed:
            sess["pending_action"] = None
            reply = "No problem! Let me know if you need anything else."
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({"stage": "declined", "reply": reply})
        
        med_name = pending.get("med_name", "Medication")
        sess["pending_action"] = None
        
        # Run vision-based scraper
        from pharmacy_scraper import scrape_all_pharmacies, PHARMACY_SITES
        try:
            results, pharmacy_screenshots = asyncio.run(scrape_all_pharmacies(med_name))
            in_stock = [r for r in results if r.get("price", 0) > 0]

            # Build search-page URLs for all known pharmacies
            pharmacy_search_urls = {p['name']: p['url_template'].format(query=med_name) for p in PHARMACY_SITES}

            # Cheapest per pharmacy (results already sorted by price ascending)
            cheapest_per_pharmacy: dict = {}
            for r in in_stock:
                ph = r.get('pharmacy', '')
                if ph not in cheapest_per_pharmacy:
                    cheapest_per_pharmacy[ph] = r

            # Overall winner
            winner_pharmacy = in_stock[0].get('pharmacy', '') if in_stock else None
            winner_price    = in_stock[0].get('price', 0)     if in_stock else None
            winner_name     = in_stock[0].get('product_name', med_name) if in_stock else None

            # Build rows for ALL pharmacies (found or not), sorted cheapest first
            pharmacy_rows = []
            found_sorted = sorted(cheapest_per_pharmacy.items(), key=lambda x: x[1]['price'])
            found_names  = [ph for ph, _ in found_sorted]

            # First add found pharmacies (sorted by price)
            for ph, item in found_sorted:
                is_winner = ph == winner_pharmacy
                pharmacy_rows.append({
                    "name":         ph,
                    "product_name": item.get('product_name', med_name),
                    "quantity":     item.get('quantity', 'N/A'),
                    "price":        item.get('price', 0),
                    "url":          pharmacy_search_urls.get(ph, '#') if is_winner else None,
                    "screenshot_url": pharmacy_screenshots.get(ph),
                    "is_winner":    is_winner,
                    "found":        True,
                })

            # Then add pharmacies with no results
            for p in PHARMACY_SITES:
                if p['name'] not in found_names:
                    pharmacy_rows.append({
                        "name":         p['name'],
                        "product_name": None,
                        "quantity":     None,
                        "price":        None,
                        "url":          None,
                        "screenshot_url": pharmacy_screenshots.get(p['name']),
                        "is_winner":    False,
                        "found":        False,
                    })

            if in_stock:
                reply = f"מצאתי את המחירים הבאים עבור **{med_name}** בבתי המרקחת:"
            else:
                reply = f"חיפשתי בבתי המרקחת אך לא מצאתי תוצאות עבור **{med_name}** כרגע."

            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({
                "stage": "med_search_complete",
                "reply": reply,
                "pharmacy_results": {
                    "med_name":        med_name,
                    "winner_pharmacy": winner_pharmacy,
                    "winner_price":    winner_price,
                    "winner_product":  winner_name,
                    "rows":            pharmacy_rows,
                } if pharmacy_rows else None
            })

        except Exception as e:
            logger.error(f"Vision search failed: {e}")
            reply = f"אירעה שגיאה בחיפוש בבתי המרקחת. נסה שוב."
            
        sess["chat_history"].append({"role": "assistant", "content": reply})
        return jsonify({"stage": "med_search_complete", "reply": reply})

    if not confirmed:
        sess["pending_action"] = None
        reply = "No problem! Let me know if you need anything else."
        sess["chat_history"].append({"role": "assistant", "content": reply})
        return jsonify({"stage": "declined", "reply": reply})

    # ── Phase 1: Scan the portal and return 3 options ─────────────────────────
    try:
        scan_result = executor.scan_appointments(pending["appointment_details"], session_id)
        options = scan_result.get("options", [])
        specialist_type = scan_result.get("specialist_type", "Family Doctor")

        if not options:
            raise RuntimeError("No appointment slots found on the portal.")

        # Store the scan result so Phase 2 can use it
        sess["pending_action"]["scanned_options"] = options
        sess["pending_action"]["specialist_type"] = specialist_type

        option_lines = "\n".join(
            f"**Option {i+1}:** {o.get('doctor')} — {o.get('clinic')} — {o.get('date')} at {o.get('time')}"
            for i, o in enumerate(options)
        )
        reply = f"I found the following available appointments:\n\n{option_lines}\n\nWhich option would you like to book? (Reply 1, 2, or 3)"
        sess["chat_history"].append({"role": "assistant", "content": reply})

        return jsonify({
            "stage": "choose_appointment",
            "reply": reply,
            "options": options,
        })

    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.route("/api/choose", methods=["POST"])
def choose():
    """Phase 2: Book the specific appointment option the user selected."""
    data = request.json or {}
    user_id    = (data.get("userId") or "").strip()
    session_id = (data.get("sessionId") or user_id or "").strip()
    choice_idx = data.get("choice")  # 0-based index

    if not session_id:
        return jsonify({"error": "sessionId is required"}), 400
    if choice_idx is None:
        return jsonify({"error": "choice index is required"}), 400

    sess = get_session(session_id, user_id)
    pending = sess.get("pending_action")
    if not pending:
        return jsonify({"error": "No pending appointment scan"}), 400

    options = pending.get("scanned_options", [])
    specialist_type = pending.get("specialist_type", "Family Doctor")

    try:
        choice_idx = int(choice_idx)
    except (TypeError, ValueError):
        return jsonify({"error": "choice must be an integer"}), 400

    if choice_idx < 0 or choice_idx >= len(options):
        return jsonify({"error": f"Invalid choice. Choose between 0 and {len(options)-1}"}), 400

    chosen = options[choice_idx]

    try:
        result = executor.execute_choice(chosen, specialist_type, session_id)
        sess["pending_action"] = None
        reply = result.get("message", "✅ Appointment booked!")
        sess["chat_history"].append({"role": "assistant", "content": reply})
        return jsonify({"stage": "booked", "reply": reply, "booking": result})
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.route("/api/history", methods=["GET"])
def history():
    """Return chat history for a user, grouped by sessions."""
    user_id = request.args.get("userId")
    if not user_id:
        return jsonify({"error": "userId required"}), 400
        
    user_history = []
    session_ids = user_sessions.get(user_id, [])
    
    for sid in session_ids:
        sess = sessions.get(sid)
        if sess and sess["chat_history"]:
            summary = sess.get("title")
            if not summary:
                # Fallback Find first user message for the summary
                summary = "New Consultation"
                for msg in sess["chat_history"]:
                    if msg["role"] == "user":
                        summary = msg["content"]
                        break
                
                # Truncate summary if too long
                if len(summary) > 60:
                    summary = summary[:57] + "..."
                
            user_history.append({
                "sessionId": sid,
                "summary": summary,
                "messages": sess["chat_history"]
            })
            
    # Reverse so newest are first
    user_history.reverse()
    
    return jsonify({"history": user_history})


@app.route("/api/medications", methods=["GET", "POST"])
def medications():
    """Handle user medication list."""
    if request.method == "POST":
        data = request.json or {}
        user_id = data.get("userId")
        meds = data.get("medications", [])
        if not user_id:
            return jsonify({"error": "userId required"}), 400
        udata = get_user_data(user_id)
        udata["medications"] = meds
        return jsonify({"success": True})
    
    user_id = request.args.get("userId")
    if not user_id:
        return jsonify({"error": "userId required"}), 400
    udata = get_user_data(user_id)
    return jsonify({"medications": udata.get("medications", [])})




@app.route("/api/reset", methods=["POST"])
def reset():
    """Clear session data for a new consultation."""
    data = request.json or {}
    session_id = (data.get("userId") or data.get("session_id") or "").strip()
    if not session_id:
        return jsonify({"error": "userId required"}), 400
    
    if session_id in sessions:
        sessions[session_id] = {
            "chat_history": [],
            "pending_action": None,
            "last_triage": None,
            "patient_profile": {
                "symptoms": [],
                "duration": "unknown",
                "relevant_history": "none",
                "medications": []
            }
        }
    return jsonify({"success": True})


if __name__ == "__main__":
    app.run(debug=True, port=5000)