"""
AhYakar — Multi-Agent Medical Assistant
========================================
Flask backend that orchestrates the four-agent pipeline:

  [1] Intake Analyst      — gatekeeper: home remedy vs escalate vs no-symptoms
  [2] Medical Advisor     — deep clinical analysis: OTC vs doctor vs emergency
  [3] Appointment Planner — finds nearest available doctor using patient location
  [4] Executor            — calls the booking API after user confirms

Session state is kept in-memory, keyed by a UUID generated by the browser
and persisted in localStorage for the duration of the tab/conversation.
"""

import os
import logging
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from flask import Flask, request, jsonify, render_template
from openai import OpenAI

from agents import intake_analyst, medical_advisor, appointment_planner, executor

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# ── OpenRouter client (lazy-initialized on first request) ──────────────────
_client: OpenAI | None = None

def get_client() -> OpenAI:
    """Return the singleton OpenRouter client, creating it on first call."""
    global _client
    if _client is None:
        api_key = os.getenv("OPENROUTER_API_KEY")
        if not api_key:
            raise RuntimeError(
                "OPENROUTER_API_KEY environment variable is not set. "
                "Please set it before starting the server."
            )
        _client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key,
        )
    return _client

# ── In-memory session store ───────────────────────────────────────────────────
# Structure: { session_id: { chat_history, pending_action, last_triage } }
sessions: dict[str, dict] = {}


def get_session(session_id: str) -> dict:
    """Return (creating if needed) the session state for the given ID."""
    if session_id not in sessions:
        sessions[session_id] = {
            "chat_history": [],
            "pending_action": None,
            "last_triage": None,
        }
    return sessions[session_id]


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def home():
    """Serve the web UI."""
    return render_template("index.html")


@app.route("/api/chat", methods=["POST"])
def chat():
    """Main pipeline endpoint."""
    data = request.json or {}
    user_message = (data.get("message") or "").strip()
    
    # Support both session_id (old) and userId (new frontend)
    session_id = (data.get("userId") or data.get("session_id") or "").strip()
    location   = data.get("location")

    if not user_message:
        return jsonify({"error": "message is required"}), 400
    if not session_id:
        return jsonify({"error": "userId/session_id is required"}), 400

    sess = get_session(session_id)
    sess["chat_history"].append({"role": "user", "content": user_message})

    try:
        client = get_client()

        # ── Agent 1: Intake Analyst ──────────────────────────────────────────
        logger.info("[%s] Agent 1 — Intake Analyst", session_id[:8])
        triage = intake_analyst.analyze(client, user_message, sess["chat_history"])
        sess["last_triage"] = triage
        
        action1 = triage.get("action", "escalate")

        if action1 == "no_symptoms":
            reply = "I'm here to help with your health! Describe any symptoms you have."
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({"stage": "chat", "reply": reply, "requires_confirm": False})

        if action1 == "home_remedy":
            reply = triage.get("home_remedy_advice") or "This sounds like it can be managed at home with rest and fluids."
            reply += "\n\n_I am an AI assistant, not a doctor._"
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({"stage": "home_remedy", "reply": reply, "requires_confirm": False})

        # ── Agent 2: Medical Advisor ─────────────────────────────────────────
        logger.info("[%s] Agent 2 — Medical Advisor", session_id[:8])
        advice = medical_advisor.advise(client, triage)
        action2 = advice.get("action", "doctor_needed")

        if action2 == "emergency":
            reply = advice.get("reply") or "🚨 **Medical Emergency.** Call 101/911 immediately."
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({"stage": "emergency", "reply": reply, "requires_confirm": False})

        if action2 == "otc":
            reply = advice.get("reply", "")
            sess["chat_history"].append({"role": "assistant", "content": reply})
            return jsonify({"stage": "otc", "reply": reply, "requires_confirm": False})

        # Doctor needed → Agent 3: Appointment Planner
        logger.info("[%s] Agent 3 — Appointment Planner", session_id[:8])
        plan_result = appointment_planner.plan(client, triage, advice, location)
        proposal_text = plan_result.get("proposal_text", "")
        
        sess["pending_action"] = {
            "appointment_details": plan_result.get("appointment_details", {}),
            "triage": triage,
        }

        advisor_reply = advice.get("reply", "")
        full_history = advisor_reply + (f"\n\n{proposal_text}" if proposal_text else "")
        sess["chat_history"].append({"role": "assistant", "content": full_history})
        
        return jsonify({
            "stage": "doctor_needed",
            "reply": advisor_reply,
            "proposal": proposal_text,
            "requires_confirm": True,
        })

    except Exception as exc:
        logger.exception("[%s] Pipeline error: %s", session_id[:8], exc)
        return jsonify({"error": str(exc)}), 500


@app.route("/api/confirm", methods=["POST"])
def confirm():
    """Confirmation endpoint for booking."""
    data = request.json or {}
    session_id = (data.get("userId") or data.get("session_id") or "").strip()
    confirmed  = bool(data.get("confirmed", False))

    if not session_id:
        return jsonify({"error": "userId is required"}), 400

    sess = get_session(session_id)
    pending = sess.get("pending_action")

    if not pending:
        return jsonify({"error": "No pending appointment"}), 400

    if not confirmed:
        sess["pending_action"] = None
        reply = "No problem! Let me know if you need anything else."
        sess["chat_history"].append({"role": "assistant", "content": reply})
        return jsonify({"stage": "declined", "reply": reply})

    # ── Agent 4: Executor ──────────────────────────────────────────────────
    try:
        result = executor.execute_booking(pending["appointment_details"], pending["triage"])
        sess["pending_action"] = None
        reply = result.get("message", "✅ Appointment booked!")
        sess["chat_history"].append({"role": "assistant", "content": reply})
        return jsonify({"stage": "booked", "reply": reply, "booking": result})
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.route("/api/history", methods=["GET"])
def history():
    """Return chat history for a user."""
    user_id = request.args.get("userId")
    if not user_id:
        return jsonify({"error": "userId required"}), 400
    sess = get_session(user_id)
    return jsonify({"history": sess["chat_history"]})


@app.route("/api/medications", methods=["GET", "POST"])
def medications():
    """Handle user medication list."""
    if request.method == "POST":
        data = request.json or {}
        user_id = data.get("userId")
        meds = data.get("medications", [])
        if not user_id:
            return jsonify({"error": "userId required"}), 400
        sess = get_session(user_id)
        sess["medications"] = meds
        return jsonify({"success": True})
    
    user_id = request.args.get("userId")
    if not user_id:
        return jsonify({"error": "userId required"}), 400
    sess = get_session(user_id)
    return jsonify({"medications": sess.get("medications", [])})


if __name__ == "__main__":
    app.run(debug=True, port=5000)
    app.run(debug=True, port=5000)